id: oi-wiki:math/powerful-number-2
name: Powerful Number
solution:
  cpp: docs/math/code/powerful-number/powerful-number_2.cpp
target:
- 'test'
testcases:
  answer: docs/math/examples/powerful-number/powerful-number_2.ans
  input: docs/math/examples/powerful-number/powerful-number_2.in
version: 1000
