id: oi-wiki:graph/diff-constraints-1
name: Diff Constraints
solution:
  cpp: docs/graph/code/diff-constraints/diff-constraints_1.cpp
target:
- 'test'
testcases:
  answer: docs/graph/examples/diff-constraints/diff-constraints_1.ans
  input: docs/graph/examples/diff-constraints/diff-constraints_1.in
version: 1000
