id: oi-wiki:basic/prefix-sum-2
name: Prefix-Sum Algorithm
solution:
  cpp: docs/basic/code/prefix-sum/prefix-sum_2.cpp
target:
- 'test'
testcases:
  answer: docs/basic/examples/prefix-sum/prefix-sum_2.ans
  input: docs/basic/examples/prefix-sum/prefix-sum_2.in
version: 1000
