id: oi-wiki:basic/prefix-sum-1
name: Prefix-Sum Algorithm
solution:
  cpp: docs/basic/code/prefix-sum/prefix-sum_1.cpp
target:
- 'test'
testcases:
  answer: docs/basic/examples/prefix-sum/prefix-sum_1.ans
  input: docs/basic/examples/prefix-sum/prefix-sum_1.in
version: 1000
