id: oi-wiki:math/lagrange-2
name: Lagrange
solution:
  cpp: docs/math/code/poly/lagrange/lagrange_2.cpp
target:
- 'test'
testcases:
  answer: docs/math/examples/poly/lagrange/lagrange_2.ans
  input: docs/math/examples/poly/lagrange/lagrange_2.in
version: 1000
