id: oi-wiki:math/interp-3
name: Interpolation
solution:
  cpp: docs/math/code/numerical/interp/interp_3.cpp
target:
- 'test'
testcases:
  answer: docs/math/examples/numerical/interp/interp_3.ans
  input: docs/math/examples/numerical/interp/interp_3.in
version: 1000
