id: oi-wiki:math/interp-1
name: Interpolation
solution:
  cpp: docs/math/code/numerical/interp/interp_1.cpp
target:
- 'test'
testcases:
  answer: docs/math/examples/numerical/interp/interp_1.ans
  input: docs/math/examples/numerical/interp/interp_1.in
version: 1000
