id: oi-wiki:ds/monotonous-queue-1
name: Monotonous Queue
solution:
  cpp: docs/ds/code/monotonous-queue/monotonous-queue_1.cpp
target:
- 'test'
testcases:
  answer: docs/ds/examples/monotonous-queue/monotonous-queue_1.ans
  input: docs/ds/examples/monotonous-queue/monotonous-queue_1.in
version: 1000
