id: oi-wiki:ds/queue-1
name: Queue
solution:
  cpp: docs/ds/code/queue/queue_1.cpp
target:
- 'test'
testcases:
  answer: docs/ds/examples/queue/queue_1.ans
  input: docs/ds/examples/queue/queue_1.in
version: 1000
