id: oi-wiki:string/trie-3
name: Trie
solution:
  cpp: docs/string/code/trie/trie_3.cpp
target:
- 'test'
testcases:
  answer: docs/string/examples/trie/trie_3.ans
  input: docs/string/examples/trie/trie_3.in
version: 1000
