id: oi-wiki:ds/seg-beats-3
name: Seg Beats
solution:
  cpp: docs/ds/code/seg-beats/seg-beats_3.cpp
target:
- 'test'
testcases:
  answer: docs/ds/examples/seg-beats/seg-beats_3.ans
  input: docs/ds/examples/seg-beats/seg-beats_3.in
version: 1000
