id: oi-wiki:dp/plug-1
name: Plug DP
solution:
  cpp: docs/dp/code/plug/plug_1.cpp
target:
- 'test'
testcases:
  answer: docs/dp/examples/plug/plug_1.ans
  input: docs/dp/examples/plug/plug_1.in
version: 1000
