id: oi-wiki:search/dlx-4
name: DLX
solution:
  cpp: docs/search/code/dlx/dlx_4.cpp
target:
- 'test'
testcases:
  answer: docs/search/examples/dlx/dlx_4.ans
  input: docs/search/examples/dlx/dlx_4.in
version: 1000
