id: oi-wiki:dp/knapsack-1
name: Knapsack DP
solution:
  cpp: docs/dp/code/knapsack/knapsack_1.cpp
target:
- 'test'
testcases:
  answer: docs/dp/examples/knapsack/knapsack_1.ans
  input: docs/dp/examples/knapsack/knapsack_1.in
version: 1000
