id: oi-wiki:misc/cdq-divide-1
name: Cdq Divide
solution:
  cpp: docs/misc/code/cdq-divide/cdq-divide_1.cpp
target:
- 'test'
testcases:
  answer: docs/misc/examples/cdq-divide/cdq-divide_1.ans
  input: docs/misc/examples/cdq-divide/cdq-divide_1.in
version: 1000
