id: oi-wiki:misc/cdq-divide-4
name: Cdq Divide
solution:
  cpp: docs/misc/code/cdq-divide/cdq-divide_4.cpp
target:
- 'test'
testcases:
  answer: docs/misc/examples/cdq-divide/cdq-divide_4.ans
  input: docs/misc/examples/cdq-divide/cdq-divide_4.in
version: 1000
