id: oi-wiki:misc/cdq-divide-3
name: Cdq Divide
solution:
  cpp: docs/misc/code/cdq-divide/cdq-divide_3.cpp
target:
- 'test'
testcases:
  answer: docs/misc/examples/cdq-divide/cdq-divide_3.ans
  input: docs/misc/examples/cdq-divide/cdq-divide_3.in
version: 1000
