id: oi-wiki:misc/hill-climbing-2
name: Hill Climbing
solution:
  cpp: docs/misc/code/hill-climbing/hill-climbing_2.cpp
target:
- 'test'
testcases:
  answer: docs/misc/examples/hill-climbing/hill-climbing_2.ans
  input: docs/misc/examples/hill-climbing/hill-climbing_2.in
version: 1000
