id: oi-wiki:graph/mod-shortest-path-1
name: Mod Shortest Path
solution:
  cpp: docs/graph/code/mod-shortest-path/mod-shortest-path_1.cpp
target:
- 'test'
testcases:
  answer: docs/graph/examples/mod-shortest-path/mod-shortest-path_1.ans
  input: docs/graph/examples/mod-shortest-path/mod-shortest-path_1.in
version: 1000
