id: oi-wiki:string/ac-automaton-2
name: Ac Automaton
solution:
  cpp: docs/string/code/ac-automaton/ac-automaton_2.cpp
target:
- 'test'
testcases:
  answer: docs/string/examples/ac-automaton/ac-automaton_2.ans
  input: docs/string/examples/ac-automaton/ac-automaton_2.in
version: 1000
