id: oi-wiki:ds/leftist-tree-3
name: Leftist Tree
solution:
  cpp: docs/ds/code/leftist-tree/leftist-tree_3.cpp
target:
- 'test'
testcases:
  answer: docs/ds/examples/leftist-tree/leftist-tree_3.ans
  input: docs/ds/examples/leftist-tree/leftist-tree_3.in
version: 1000
