id: oi-wiki:misc/fsm-2
name: Fsm
solution:
  cpp: docs/misc/code/fsm/fsm_2.cpp
target:
- 'test'
testcases:
  answer: docs/misc/examples/fsm/fsm_2.ans
  input: docs/misc/examples/fsm/fsm_2.in
version: 1000
