id: oi-wiki:ds/ett-subtree-size
name: ETT_SUBTREE
solution:
  cpp: docs/ds/code/ett/ett_subtree_size.cpp
target:
- 'test'
testcases:
  answer: docs/ds/examples/ett/ett_subtree_size.ans
  input: docs/ds/examples/ett/ett_subtree_size.in
version: 1000
