id: oi-wiki:math/min-25-1
name: Min 25
solution:
  cpp: docs/math/code/min-25/min-25_1.cpp
target:
- 'test'
testcases:
  answer: docs/math/examples/min-25/min-25_1.ans
  input: docs/math/examples/min-25/min-25_1.in
version: 1000
