id: oi-wiki:ds/top-tree-1
name: Top Tree
solution:
  cpp: docs/ds/code/top-tree/top-tree_1.cpp
target:
- 'test'
testcases:
  answer: docs/ds/examples/top-tree/top-tree_1.ans
  input: docs/ds/examples/top-tree/top-tree_1.in
version: 1000
