id: oi-wiki:topic/segment-tree-offline/segment-tree-offline_2
name: Segment Tree Offline 2
solution:
  cpp: docs/topic/code/segment-tree-offline/segment-tree-offline_2.cpp
target:
- 'test'
testcases:
  answer: docs/topic/examples/segment-tree-offline/segment-tree-offline_2.ans
  input: docs/topic/examples/segment-tree-offline/segment-tree-offline_2.in
version: 1000