id: oi-wiki:ds/binary-heap-1
name: Binary Heap
solution:
  cpp: docs/ds/code/binary-heap/binary-heap_1.cpp
target:
- 'test'
testcases:
  answer: docs/ds/examples/binary-heap/binary-heap_1.ans
  input: docs/ds/examples/binary-heap/binary-heap_1.in
version: 1000
