id: oi-wiki:graph/graph-matching/bigraph-weight-match_1
name: BiGraph Weight Match 1
solution:
  cpp: docs/graph/graph-matching/code/bigraph-weight-match/bigraph-weight-match_1.cpp
target:
- 'test'
testcases:
  answer: docs/graph/graph-matching/examples/bigraph-weight-match/bigraph-weight-match_1.ans
  input: docs/graph/graph-matching/examples/bigraph-weight-match/bigraph-weight-match_1.in
version: 1000