id: oi-wiki:string/general-sam-2
name: General Sam
solution:
  cpp: docs/string/code/general-sam/general-sam_2.cpp
target:
- 'test'
testcases:
  answer: docs/string/examples/general-sam/general-sam_2.ans
  input: docs/string/examples/general-sam/general-sam_2.in
version: 1000
