id: oi-wiki:graph/bfs-1
name: BFS
solution:
  cpp: docs/graph/code/bfs/bfs_1.cpp
target:
- 'test'
testcases:
  answer: docs/graph/examples/bfs/bfs_1.ans
  input: docs/graph/examples/bfs/bfs_1.in
version: 1000
