name: "Celebration"

on:
  workflow_dispatch:
  watch:
    types:
      - started

jobs:
  celebrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pipenv
      - name: Install Python dependencies
        run: |
          curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python3
          pipenv install
      - name: Celebrate
        run: pipenv run python scripts/celebration.py "${{ secrets.GITHUB_TOKEN }}"
