name: "Celebration"

on:
  workflow_dispatch:
  push:
  watch:
    types:
      - started

jobs:
  celebrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python scripts/celebration.py
