name: Check code coverage of scripts

on:
  pull_request:
    branches:
      - master

jobs:
  remark-lint:
    name: Check code coverage of Python scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install uv
          uv sync
          uv sync --dev
      
      - name: Report code coverage
        run: |
          uv run coverage run -m unittest
          uv run coverage report -m
