name: Check Config Files

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: OI-Wiki Config Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pipenv
      - name: Install Python Dependencies
        run: |
          pip install pipenv
          pipenv install
      - name: Make Config Files List
        run: find ./docs -name "*.yml" > config.txt
      - name: Check Config Files
        run: pipenv run python scripts/check-config.py
