name: Add new archive links

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master
      - uses: actions/checkout@v4
        with:
          ref: archiveLink
          path: scripts/archive-link/data
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install Python dependencies
        run: pip install -r scripts/archive-link/requirements.txt
      - name: Update data.json based on latest commit
        run: python -u scripts/archive-link/archiveNewLink.py
      - name: Upload data.json
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name github-actions
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -a -m "Update the status of each links on $(date '+%Y-%m-%d %H:%M:%S')"
            git push origin archiveLink
          else
            echo "No changes to commit."
          fi
        working-directory: scripts/archive-link/data
      
      
