id: oi-wiki:math/fft-1
name: FFT
solution:
  cpp: docs/math/code/poly/fft/fft_1.cpp
target:
- 'test'
testcases:
  answer: docs/math/examples/poly/fft/fft_1.ans
  input: docs/math/examples/poly/fft/fft_1.in
version: 1000
