id: oi-wiki:math/fft-2
name: FFT
solution:
  cpp: docs/math/code/poly/fft/fft_2.cpp
target:
- 'test'
testcases:
  answer: docs/math/examples/poly/fft/fft_2.ans
  input: docs/math/examples/poly/fft/fft_2.in
version: 1000
